import './globals.css'
import { Quicksand } from 'next/font/google';

const quicksand = Quicksand({ 
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
